apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: student
  template:
    metadata:
      labels:
        app: student
    spec:
      containers:
      - name: student-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080